# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '主界面.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(930, 703)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.cust_name = QtWidgets.QLineEdit(self.centralwidget)
        self.cust_name.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cust_name.setObjectName("cust_name")
        self.horizontalLayout_4.addWidget(self.cust_name)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.cust_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.cust_phone.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cust_phone.setObjectName("cust_phone")
        self.horizontalLayout_4.addWidget(self.cust_phone)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(3000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.thing_name = QtWidgets.QLineEdit(self.centralwidget)
        self.thing_name.setMinimumSize(QtCore.QSize(200, 30))
        self.thing_name.setInputMask("")
        self.thing_name.setText("")
        self.thing_name.setObjectName("thing_name")
        self.horizontalLayout_3.addWidget(self.thing_name)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.showYaopin = QtWidgets.QTableWidget(self.tab)
        self.showYaopin.setObjectName("showYaopin")
        self.showYaopin.setColumnCount(0)
        self.showYaopin.setRowCount(0)
        self.horizontalLayout_7.addWidget(self.showYaopin)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.showShoufa = QtWidgets.QTableWidget(self.tab_2)
        self.showShoufa.setObjectName("showShoufa")
        self.showShoufa.setColumnCount(0)
        self.showShoufa.setRowCount(0)
        self.horizontalLayout_8.addWidget(self.showShoufa)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_vaild = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.name_vaild.setFont(font)
        self.name_vaild.setObjectName("name_vaild")
        self.horizontalLayout.addWidget(self.name_vaild)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.money_vaild = QtWidgets.QLCDNumber(self.centralwidget)
        self.money_vaild.setMinimumSize(QtCore.QSize(200, 100))
        self.money_vaild.setObjectName("money_vaild")
        self.horizontalLayout.addWidget(self.money_vaild)
        spacerItem4 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.jifen = QtWidgets.QLCDNumber(self.centralwidget)
        self.jifen.setMinimumSize(QtCore.QSize(200, 100))
        self.jifen.setObjectName("jifen")
        self.horizontalLayout.addWidget(self.jifen)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMaxLength(1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 930, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.add_things = QtWidgets.QAction(mainWindow)
        self.add_things.setObjectName("add_things")
        self.edit_things = QtWidgets.QAction(mainWindow)
        self.edit_things.setObjectName("edit_things")
        self.print_things = QtWidgets.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/print.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.print_things.setIcon(icon1)
        self.print_things.setObjectName("print_things")
        self.refreash = QtWidgets.QAction(mainWindow)
        self.refreash.setObjectName("refreash")
        self.import_CSV = QtWidgets.QAction(mainWindow)
        self.import_CSV.setObjectName("import_CSV")
        self.get_all_activities = QtWidgets.QAction(mainWindow)
        self.get_all_activities.setObjectName("get_all_activities")
        self.my_people = QtWidgets.QAction(mainWindow)
        self.my_people.setObjectName("my_people")
        self.action_2 = QtWidgets.QAction(mainWindow)
        self.action_2.setObjectName("action_2")
        self.look_Cust = QtWidgets.QAction(mainWindow)
        self.look_Cust.setObjectName("look_Cust")
        self.menu.addAction(self.print_things)
        self.menu.addAction(self.refreash)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.add_things)
        self.menu_2.addAction(self.edit_things)
        self.menu_2.addAction(self.import_CSV)
        self.menu_3.addAction(self.my_people)
        self.menu_3.addAction(self.look_Cust)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "系统主界面"))
        self.label.setText(_translate("mainWindow", "名字"))
        self.label_2.setText(_translate("mainWindow", "电话"))
        self.pushButton.setText(_translate("mainWindow", "搜索"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "药品"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "手法"))
        self.name_vaild.setText(_translate("mainWindow", "余额"))
        self.label_4.setText(_translate("mainWindow", "积分"))
        self.lineEdit.setInputMask(_translate("mainWindow", "1"))
        self.lineEdit.setText(_translate("mainWindow", "1"))
        self.pushButton_2.setText(_translate("mainWindow", "结账"))
        self.menu.setTitle(_translate("mainWindow", "文件"))
        self.menu_2.setTitle(_translate("mainWindow", "编辑"))
        self.menu_3.setTitle(_translate("mainWindow", "数据"))
        self.menu_4.setTitle(_translate("mainWindow", "关于"))
        self.add_things.setText(_translate("mainWindow", "添加商品"))
        self.edit_things.setText(_translate("mainWindow", "编辑商品"))
        self.print_things.setText(_translate("mainWindow", "打印"))
        self.refreash.setText(_translate("mainWindow", "刷新"))
        self.refreash.setShortcut(_translate("mainWindow", "F4"))
        self.import_CSV.setText(_translate("mainWindow", "导入CSV"))
        self.get_all_activities.setText(_translate("mainWindow", "商业活动"))
        self.my_people.setText(_translate("mainWindow", "员工薪酬"))
        self.action_2.setText(_translate("mainWindow", "添加用户"))
        self.look_Cust.setText(_translate("mainWindow", "查看用户记录"))
import image_rc
